apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: fencing-agent

namespace: fencing-agent

resources:
  - ./namespace.yaml
  - ./daemonset.yaml
  - ./rbac-for-us.yaml

